/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TokensTokenIdRouteImport } from './routes/tokens/$tokenId'
import { Route as ApiTokensRouteImport } from './routes/api.tokens'
import { Route as ApiFrameworkRouteImport } from './routes/api.framework'
import { Route as ApiTokensTokenIdRouteImport } from './routes/api.tokens.$tokenId'

const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensTokenIdRoute = TokensTokenIdRouteImport.update({
  id: '/tokens/$tokenId',
  path: '/tokens/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokensRoute = ApiTokensRouteImport.update({
  id: '/api/tokens',
  path: '/api/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFrameworkRoute = ApiFrameworkRouteImport.update({
  id: '/api/framework',
  path: '/api/framework',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokensTokenIdRoute = ApiTokensTokenIdRouteImport.update({
  id: '/$tokenId',
  path: '/$tokenId',
  getParentRoute: () => ApiTokensRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/api/framework': typeof ApiFrameworkRoute
  '/api/tokens': typeof ApiTokensRouteWithChildren
  '/tokens/$tokenId': typeof TokensTokenIdRoute
  '/api/tokens/$tokenId': typeof ApiTokensTokenIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/api/framework': typeof ApiFrameworkRoute
  '/api/tokens': typeof ApiTokensRouteWithChildren
  '/tokens/$tokenId': typeof TokensTokenIdRoute
  '/api/tokens/$tokenId': typeof ApiTokensTokenIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/api/framework': typeof ApiFrameworkRoute
  '/api/tokens': typeof ApiTokensRouteWithChildren
  '/tokens/$tokenId': typeof TokensTokenIdRoute
  '/api/tokens/$tokenId': typeof ApiTokensTokenIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/api/framework'
    | '/api/tokens'
    | '/tokens/$tokenId'
    | '/api/tokens/$tokenId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/api/framework'
    | '/api/tokens'
    | '/tokens/$tokenId'
    | '/api/tokens/$tokenId'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/api/framework'
    | '/api/tokens'
    | '/tokens/$tokenId'
    | '/api/tokens/$tokenId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  ApiFrameworkRoute: typeof ApiFrameworkRoute
  ApiTokensRoute: typeof ApiTokensRouteWithChildren
  TokensTokenIdRoute: typeof TokensTokenIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/$tokenId': {
      id: '/tokens/$tokenId'
      path: '/tokens/$tokenId'
      fullPath: '/tokens/$tokenId'
      preLoaderRoute: typeof TokensTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tokens': {
      id: '/api/tokens'
      path: '/api/tokens'
      fullPath: '/api/tokens'
      preLoaderRoute: typeof ApiTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/framework': {
      id: '/api/framework'
      path: '/api/framework'
      fullPath: '/api/framework'
      preLoaderRoute: typeof ApiFrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tokens/$tokenId': {
      id: '/api/tokens/$tokenId'
      path: '/$tokenId'
      fullPath: '/api/tokens/$tokenId'
      preLoaderRoute: typeof ApiTokensTokenIdRouteImport
      parentRoute: typeof ApiTokensRoute
    }
  }
}

interface ApiTokensRouteChildren {
  ApiTokensTokenIdRoute: typeof ApiTokensTokenIdRoute
}

const ApiTokensRouteChildren: ApiTokensRouteChildren = {
  ApiTokensTokenIdRoute: ApiTokensTokenIdRoute,
}

const ApiTokensRouteWithChildren = ApiTokensRoute._addFileChildren(
  ApiTokensRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  ApiFrameworkRoute: ApiFrameworkRoute,
  ApiTokensRoute: ApiTokensRouteWithChildren,
  TokensTokenIdRoute: TokensTokenIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
